### ISSUE TITLE
why not PR?

### ISSUE THREAD

**Issue by Be1zebub** [Pika-Software/gmod_rebase#3]
why separate repository?
PR [facepunch/garrysmod](https://github.com/facepunch/garrysmod) would be much better.
or at least [facepunch/garrysmod](https://github.com/facepunch/garrysmod) fork, so that we can see what you have changed in the base gamemode

**Comment by unknown-gd** [comment]
First of all it is an addon, PR no one will accept, Rubat certainly not, he will say some nonsense about security and that he is too lazy to check. The whole structure of the base mode was rewritten by me from scratch with a set of small changes outside of it.

**Comment by Be1zebub** [comment]
"no one will accept" - did you try?
anyway, if you dont want to make PR - just make a fork, i want to audit your re-base - but i cant see whats you changed.

**Comment by unknown-gd** [comment]
fork does not work that way, you will not see changes, or rather you will see that all files have been deleted and new ones created, if you want to see the code, look, fork will not help you at all. Now about Rubat, i hate him, I'm not going to do an updates for him.

**Comment by dankmolot** [comment]
But we aren't doing things for Rubat, we are doing them for community. Forking garrysmod repository is probably good idea. @PrikolMen

**Comment by unknown-gd** [comment]
@dankmolot If I do a fork, it won't be re:base, it will be re:garrysmod or something like that...

**Comment by Be1zebub** [comment]
ru shure? i have a https://github.com/parkervcp/yolks fork: https://github.com/Be1zebub/luvit-pterodactyl
there is no problem to change repo name

**Comment by Be1zebub** [comment]
dont delete all files, just make a fork, delete all except garrysmod/base & replace files in it - then we will see changes in commit

**Comment by Be1zebub** [comment]
We discussed this issue in discord https://discord.incredible-gmod.ru/ because its more convenient to have a long discussion.  
if you are interested, you can read it here: https://discord.com/channels/559055559261814836/676068972185255987/1042884332865458197  
Conclusion: fork/pr will not be because rebase is a gamemodes/base written from scratch - with a different structure that is backward incompatible.  
I plan to make my facepunch/garrysmod fork and move all the changes from rebase there, so that it would be easy to merge.  
What for? It will be possible to see the changes history, it will be possible to merge it, the project will never die.
I'll mention my fork here when I do that.
